// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1MJB_cQ2gogqJWq1oT1vun3xfxT-SaI',
    appId: '1:377726774421:web:a09c49c0c4e539d7903f9c',
    messagingSenderId: '377726774421',
    projectId: 'authexample-eb3eb',
    authDomain: 'authexample-eb3eb.firebaseapp.com',
    storageBucket: 'authexample-eb3eb.appspot.com',
    measurementId: 'G-CHK6K14NPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHxJgCC-HozekVF8w8g4m6I2WvSoLAlx4',
    appId: '1:377726774421:android:f54979633bf79261903f9c',
    messagingSenderId: '377726774421',
    projectId: 'authexample-eb3eb',
    storageBucket: 'authexample-eb3eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfgW58sPxZbmDSHBShcKFlz3IJtiFC-ws',
    appId: '1:377726774421:ios:acb87c38e0be5901903f9c',
    messagingSenderId: '377726774421',
    projectId: 'authexample-eb3eb',
    storageBucket: 'authexample-eb3eb.appspot.com',
    iosClientId:
        '377726774421-m7u3774ia2mhb9oactm1rapjbgq9noc0.apps.googleusercontent.com',
    iosBundleId: 'com.example.authExample',
  );
}
